version: '3.6'
services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '127.0.0.1:2375:2375'
    environment:
      - LOG_LEVEL=debug # debug,info,notice,warning,err,crit,alert,emerg
      - CONTAINERS=1
      - INFO=1

  telegraf:
    privileged: true
    container_name: telegraf
    platform: linux/x86_64
    image: telegraf:1.18-alpine
    user: telegraf:1
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '127.0.0.1:8125:8125/udp'


  influxdb:
    privileged: true
    container_name: influxdb
    platform: linux/x86_64
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    privileged: true
    container_name: grafana
    platform: linux/x86_64
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

  nginx:
    platform: linux/x86_64
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/html/:/usr/share/nginx/html/
      - ./nginx/conf/:/etc/nginx/conf.d/
    ports:
      - '127.0.0.1:8080:80'
    depends_on:
      - php
      - mongo

  php:
    build:
      context: .
      dockerfile: php.DockerFile
    container_name: php
    volumes:
      - ./nginx/html/:/usr/share/nginx/html/

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '127.0.0.1:27017:27017'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data

volumes:
  grafana_data: {}
  influxdb_data: {}
  elastic: {}
